app = "genie-sidekick"
primary_region = "iad"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[build]
  dockerfile = "dockerfile"

[env]
  PORT = "8001"
  PYTHONUNBUFFERED = "1"

[[vm]]
  size = "shared-cpu-1x"
  cpu_kind = "shared"
  cpus = 1
  memory = "1024mb"
