# fly.toml app configuration file generated for realwah-lah-com on 2026-07-17T00:36:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'realwah-lah-com'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]
  dockerfile = 'dockerfile'

[env]
  PORT = '8001'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '20s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
