<<<<<<< HEAD
# fly.toml app configuration file generated for wah-lah on 2026-07-17T00:56:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wah-lah"
=======
app = "realwah-lah-com"
>>>>>>> codespace-trout
primary_region = "iad"
kill_signal = "SIGTERM"
kill_timeout = "30s"

<<<<<<< HEAD
=======
[build]
  dockerfile = "Dockerfile"

>>>>>>> codespace-trout
[env]
  PORT = "8001"
  PYTHONUNBUFFERED = "1"

<<<<<<< HEAD
[build]
  dockerfile = "dockerfile"

=======
>>>>>>> codespace-trout
[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
<<<<<<< HEAD
  processes = ['app']
  checks = [{ grace_period = '30s', interval = '20s', method = 'GET', path = '/api/health', timeout = '5s' }]
  concurrency = { hard_limit = 250, soft_limit = 200, type = 'requests' }
=======
  processes = ["app"]
>>>>>>> codespace-trout

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = "20s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/api/health"

[[vm]]
<<<<<<< HEAD
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  cpus = 1
  memory = '1024mb'

[processes]
  app = ''
=======
  size = "shared-cpu-1x"
  cpu_kind = "shared"
  cpus = 1
  memory = "1024mb"
>>>>>>> codespace-trout
